#mysql连接配置
mysql:
  driverName: mysql
  dataSourceName: douyin:abc123456+@tcp(81.68.239.206:3306)/douyin?parseTime=true

#redis配置
redis:
  url: 81.68.239.206:6379
  password: tanyongfeng13666
  database: 1  # using database 2

#gin配置
server:
  port: 8080
  runMode: debug
  ReadTimeout: 60
  WriteTimeout: 60




