#mysql连接配置
mysql:
  DBType: mysql
  Username: douyin  # 填写你的数据库账号
  Password: abc123456+  # 填写你的数据库密码
  Host: 81.68.239.206:3306
  DBName: douyin
  TablePrefix: dy_
  Charset: utf8
  ParseTime: True
  MaxIdleConns: 10
  MaxOpenConns: 30

#redis配置
redis:
  url: 81.68.239.206:6379
  password: tanyongfeng13666
  database: 1  # using database 2

#gin配置
server:
  runMode: debug
  port: 8080
  ReadTimeout: 60
  WriteTimeout: 60
  
#log日志的配置
log:
  level: debug
  log_path: storage/logs
  filename: douyin.log
  max_size: 200 #最大文件大小
  max_age : 60  #存放时间
  max_backups: 5 #最大的备份数



