#mysql连接配置
mysql:
  DBType: mysql
  Username: root
  Password: 123
  Host: 127.0.0.1:3306
  DBName: douyin
  TablePrefix: dy_
  Charset: utf8
  ParseTime: True
  MaxIdleConns: 10
  MaxOpenConns: 30

#redis配置
redis:
  url: 81.68.239.206:6379
  password: tanyongfeng13666
  database: 1  # using database 1

#gin配置
server:
  runMode: debug
  port: 8080
  ReadTimeout: 60
  WriteTimeout: 60
  
#log日志的配置
log:
  level: debug
  log_path: storage/logs
  filename: douyin.log
  max_size: 200 #最大文件大小
  max_age : 60  #存放时间
  max_backups: 5 #最大的备份数

#OSS配置
oss:
  endpoint: https://oss-accelerate.aliyuncs.com
  accessKeyId: LTAI4FysLakF4dQbPPJakWia
  accessKeySecret: TbSZ2mcpDLYvDocbd5s949MThLcUYX
  bucketName: kauizhaotan
  targetPath: douyin/video/
  targetUrl: https://kauizhaotan.oss-accelerate.aliyuncs.com #配置回传视频地址前缀


